### ISSUE TITLE
Not real Islam

### ISSUE THREAD

**Issue by liverfail** [mblouka/kaabot#1]
Ahmadiyya is a religious cult movement from the 19th century, and should not be taken as actual Islamic knowledge, it would be better to source information from Sunni sources (since they make up almost the entirety of the Ummah) or rather provide the ability to pick information from different sects.

Please be extremely careful when dealing with information related to the Qur'an, Sunnah, and authentic hadiths.

Qur'an (Sahih International translation) 2:42: And do not mix the truth with falsehood or conceal the truth while you know [it].

Edit: After taking a closer look of the Ahmadiyyah cult, it is clear that they are indeed following falsehood, as the Mahdi is prophesied to have the same first name as the Prophet Muhammad ﷺ with the father of the Mahdi having the same first name as the Prophet ﷺ's Father (Abd-Allah/Abdullah), the Ahmadiyyah believe Mirza Ghulam Ahmad is the Mahdi, which contradicts the prophecies given to us by the Prophet Muhammad ﷺ

**Comment by loukamb** [comment]
Assalamo alaykum. Ahmadi Islam is compatible with the vast majority of Sunni practices. Most of the hadiths followed in Ahmadi Islam are also those accepted by Sunni muslims. Beware of the prejudice sadly fervent in the muslim world, creating stupid lies such as how we apparently pray with our back facing the Kaaba, or how we apparently do not believe Muhammad (s.a.) is the last law-bearing prophet, or how we apparently do not follow the five pillars of Islam. These are entirely factitious and are meant to denigrate and suppress Ahmadis, both for religious and also political gain. 

Do not forget that as we can observe from history, and as prophesized by almost every scripture, each new rightful and correct development of religion initially starts persecuted, e.g. the Jews in ancient history (Egypt), the early Christians in the times of the Romans, Muhammad (s.a.) and his followers in Mecca... the next one always persecuted by those who have been; Christians persecuted by the Jews, and the Muslims persecuted by the Christians. [And who is being, in this very day and age, persecuted by the Muslims?](https://en.wikipedia.org/wiki/Persecution_of_Ahmadis)

Persecution aside - where we differ in the theology (compared against Sunni islam) is the recognition and acceptance of Hazrat Mirza Ghulam Ahmad (a.s.) as the promised Messiah. It isn't a "new" prophet with new laws, it is the return of a previous one reaffirming Islamic law and peace. While there are many reasons why we believe Hazrat Mirza Ghulam Ahmad (a.s.) is the promised Messiah, ranging from the fulfillment of prophecies to signs, Github issues are _not_ a place for theological debate and I will keep this short by simply referring to the Holy Quran.

Allah says in the Holy Quran:
> “He it is Who has raised among the unlettered people a Messenger from among themselves who recites unto them His Signs, and purifies them, and teaches them the Book and Wisdom though before that they were in manifest error; And He will raise him among others of them who have not yet joined them. He is the Mighty, the Wise.” 
(Surah Al-Jumuah [62:3-4)](https://www.openquran.com/62:3-4)

A companion of [The Holy Prophet (s.a.)](https://www.alislam.org/holyprophet/) relates:
> One day we were sitting with The Holy Prophet (s.a.) when this chapter was revealed. I enquired from Muhammad (s.a.). Who are the people to whom the words and among others of them who have not yet joined them refer? Salman (r.a.), a Persian was sitting among us. The Holy Prophet (s.a.) put his hand on Salman (r.a.) and said. If faith were to go up to the Pleiades, a man from among these would surely find it. 
(Bukhari).

The advent of The Holy Prophet (s.a.) is described metaphorically as the appearance of God Almighty. The Holy Prophet (s.a.) became the mirror reflecting Divine Attributes. He was Al-Abd. The Holy Quran calls him Abdullah — The Servant of Allah. For the latter days God in His Mercy sent us the servant of The Servant — Ghulam Ahmad (s.a.). Mirza Ghulam Ahmad Qadiani (a.s.) claimed to be a prophet who was The Promised Messiah and Mahdi. Ahmad (a.s.) claimed to be the metaphorical second coming of Jesus (a.s.) of Nazareth and the divine guide, whose advent was foretold by the Prophet of Islam, Muhammad (s.a.).

Concerning the issue of the name, the Holy Quran refers to The Promised Messiah (a,s,) as a prophet who will testify to the truth of The Holy Prophet (s,a,) in the words … and will be followed by a witness from Him ([11:18](https://www.openquran.com/search?query=11%3A18)) and … *giving glad tidings of a Messenger who will come after me whose name will be Ahmad* ([61:7](https://www.openquran.com/search?query=61%3A7)).

I suggest reading more about the topic if you are interested. As a non-Ahmadi, this can simply do two things: either reaffirm your current faith, or teach you new things. I suggest starting with the following resources:
- https://whyahmadi.org/
- https://whyahmadi.org/topics/claims-of-promised-messiah
- https://whyahmadi.org/topics/objections-raised
- https://whyahmadi.org/topics/converts-accounts
- https://www.askahmadiyyat.org/
- https://www.alislam.org/

As I said earlier, GitHub issues are _not_ the place for religious discussion. Issues are for _technical_ issues with the software. The bot citing from Ahmadi libraries should not be an issue for any (Sunni) muslim because we follow the same Holy Quran and mostly the same hadiths. As this is not a proper place for theological discussion, I will now close this issue.
